export const diagnosticText: Record<string, { title: string; detail: string; action: string }> = {
  WIRE_EDIT_UNAVAILABLE: { title: '이 위치에서는 연결을 바꿀 수 없어요', detail: '삽입 공간이 부족하거나 연결 경로·참조가 모호합니다.', action: '꺾임과 교차에서 떨어진 구간을 선택하세요. 교차 분리는 주석·기준점이 없는 네 갈래에서 사용할 수 있습니다.' },
  WIRE_CURRENT_UNDEFINED: { title: '이 도선의 전류는 하나로 정해지지 않아요', detail: '저항이 없는 도선끼리 고리를 이루고 있습니다.', action: '연결된 부품에서 측정해 주세요.' },
  INCOMPLETE_PROBE: { title: '두 탐침을 연결해 주세요', detail: '빨강과 검정 탐침이 모두 연결되어야 전위차를 구합니다.', action: '탐침 위치를 각각 선택하세요.' },
  MEASUREMENT_UNAVAILABLE: { title: '측정값을 확정할 수 없어요', detail: '선택한 위치의 전위 또는 가지 전류가 정의되지 않았습니다.', action: '기준점과 회로 진단을 확인하세요.' },
  INVALID_RESISTANCE_PORT: { title: '저항 측정 포트를 확인하세요', detail: '두 측정 지점 또는 제외한 외부 전원을 찾을 수 없습니다.', action: '현재 회로의 두 지점을 다시 선택하세요.' },
  RESISTANCE_OPEN: { title: '두 점 사이가 개방되어 있어요', detail: '시험 전류가 흐를 도전 경로가 없습니다.', action: '스위치와 연결 경로를 확인하세요.' },
  RESISTANCE_SHORT: { title: '두 점 사이가 0 Ω으로 연결되어 있어요', detail: '도선 또는 비활성화한 이상적 전원이 두 점을 연결합니다.', action: '부하와 전체 회로 측정 대상의 차이를 확인하세요.' },
  PATH_NOT_CLOSED: { title: '전류가 흐르는 폐경로를 선택하세요', detail: '경로가 닫히지 않았거나 열린 스위치·전압계를 포함합니다.', action: '연속으로 연결된 닫힌 경로를 선택하세요.' },
  INVALID_PATH: { title: '경로 연결을 확인하세요', detail: '지정한 부품과 절점이 이어지지 않습니다.', action: '연결 순서대로 부품을 선택하세요.' },
  CONSERVATION_RESIDUAL: { title: '보존 법칙의 잔차가 커요', detail: '항의 합이 허용오차를 넘었습니다.', action: '회로와 수치 해석 진단을 확인하세요.' },
  MEASUREMENT_TARGET_NOT_FOUND: { title: '측정 대상을 선택하세요', detail: '선택한 가지가 현재 회로에 없습니다.', action: '현재 회로의 부품을 다시 선택하세요.' },
  INVALID_AMMETER_INSERTION: { title: '이 위치에 전류계를 삽입할 수 없어요', detail: '단자 구성이나 계기 연결이 올바르지 않습니다.', action: '연결된 두 단자 부품의 가지를 선택하세요.' },
  EMPTY_CIRCUIT: { title: '첫 회로를 만들어 보세요', detail: '전원과 저항을 놓고 단자를 연결하면 계산됩니다.', action: '부품을 선택한 뒤 캔버스에 놓으세요.' },
  FLOATING_SUBCIRCUIT: { title: '전위를 정할 수 없는 부분이 있어요', detail: '기준점이 없거나 기준점과 전기적으로 이어지지 않은 영역입니다.', action: '0 V 기준점을 지정하고 빠진 배선을 연결하세요.' },
  SOURCE_SHORT: { title: '전원이 단락되어 있어요', detail: '전원 양단을 0 Ω 경로로 연결하면 유한한 전류를 정할 수 없습니다.', action: '직접 연결된 도선을 제거하거나 저항을 추가하세요.' },
  AMMETER_PARALLEL_TO_SOURCE: { title: '전류계가 전원과 병렬로 연결되었어요', detail: '이상적인 전류계의 내부저항은 0 Ω입니다.', action: '전류계를 측정할 가지에 직렬로 삽입하세요.' },
  CONFLICTING_SOURCES: { title: '전원의 전압 조건이 충돌해요', detail: '이상적인 전원들이 같은 경로에 서로 다른 전압을 요구합니다.', action: '전원 방향과 전압을 확인하고 충돌하는 연결을 수정하세요.' },
  SINGULAR_SYSTEM: { title: '전류를 하나의 값으로 정할 수 없어요', detail: '병렬 0 Ω 경로나 중복 전원 제약으로 해가 유일하지 않을 수 있습니다.', action: '중복된 이상적 경로를 제거하거나 적절한 저항을 넣으세요.' },
  ILL_CONDITIONED_SYSTEM: { title: '안정적인 수치 해를 얻지 못했어요', detail: '계산 잔차가 허용 오차를 넘었습니다.', action: '극단적인 부품값과 회로 연결을 확인하세요.' },
  UNCONNECTED_TERMINAL: { title: '연결되지 않은 단자가 있어요', detail: '도선이 연결되지 않은 단자입니다.', action: '단자를 선택해 필요한 도선을 연결하세요.' },
  INVALID_COMPONENT_VALUE: { title: '부품값을 확인해 주세요', detail: '저항은 0 이상, 전압은 유한한 숫자여야 합니다.', action: '부품을 선택하고 유효한 값을 입력하세요.' },
  UNSUPPORTED_TERMINALS: { title: '지원하지 않는 단자 구성이에요', detail: '현재 모델은 두 단자 부품과 명시적인 전원 극성을 사용합니다.', action: '파일의 부품 단자 구성을 확인하세요.' },
  INVALID_DOCUMENT: { title: '회로 파일 형식이 올바르지 않아요', detail: '현재 파일은 edu-circuit v1 형식이어야 합니다.', action: '올바른 JSON 파일을 다시 선택하세요. 현재 회로는 유지됩니다.' },
  INVALID_REFERENCE: { title: '연결 대상이 존재하지 않아요', detail: '도선이나 주석이 삭제된 단자 또는 분기점을 가리킵니다.', action: '해당 연결을 수정하세요.' },
  DUPLICATE_ID: { title: '같은 식별자가 중복되었어요', detail: '회로의 부품·단자·도선 식별자는 고유해야 합니다.', action: 'JSON 파일에서 중복 식별자를 수정하세요.' },
};
